---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Set up development pre-reqs on a local machine
  hosts: dev
  become: yes
  roles:
    - setup_fpm
    - { role: setup_openvpn, state: 'stopped' }

  # post_tasks run after roles
  post_tasks:
    - include: base.yml

    - include: openbts.yml

    - name: Remove production Etage repo
      apt_repository: repo='deb http://repo.etagecom.io stable main' state=absent update_cache=no

    - name: Make sure (empty) local repo structure exists
      become: no
      shell: mkdir -p ~/endaga-packages/dists/localdev/main/binary-i386/

    - name: Make sure (empty) local repo Packages file exists
      become: no
      shell: touch ~/endaga-packages/dists/localdev/main/binary-i386/Packages

    - name: Add local repo (for local development)
      apt_repository: repo='deb file:/home/vagrant/endaga-packages localdev main' state=present update_cache=no mode=664

    - name: Set the local development repo to order 30
      shell: sudo mv /etc/apt/sources.list.d/file_home_vagrant_endaga_packages.list /etc/apt/sources.list.d/30_file_home_vagrant_endaga_packages.list || exit 0

    - name: Set the version preferences
      copy: src=files/endaga-preferences dest=/etc/apt/preferences.d/endaga-preferences

    - name: Setup build requirements for OpenBTS and FS packages
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - build-essential
          - libtool
          - autoconf
          - debhelper
          - pkg-config
          - devscripts
          - dpkg-dev
          - equivs
          - python-dev
          - libxmlrpc-c++8-dev
          - libftdi-dev
          - libjpeg-dev
          - libcurl4-openssl-dev
          - libpcre3-dev
          - libspeexdsp-dev
          - libldns-dev
          - libedit-dev

    - name: Setup build requirements for python packages
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - python-pip
          - python-pybabel

    - name: Setup requirements for building FS from source (needed to generate working python modules)
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - libsqlite3-dev

    - name: Setup requirements for building psycopg2 from source
      apt: pkg=libpq-dev state=present update_cache=no

    - name: Add the key for the nodesource apt repository
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    - name: Add the nodesource repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main'
        update_cache: yes

    - name: Install nodejs
      apt: name=nodejs
