# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :nitb, autostart: false do |nitb|
    nitb.vm.box = "debian/contrib-stretch64"
    nitb.vm.hostname = "nitb"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    nitb.vm.network "private_network", ip: "192.168.99.10"
    nitb.vm.synced_folder "./" , "/home/vagrant/nitb"

    nitb.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]

      # Pass through USB control of attached USRP
      vb.customize ['modifyvm', :id, '--usb', 'on']
      vb.customize ['modifyvm', :id, '--usbehci', 'on']
      vb.customize ['modifyvm', :id, '--usbxhci', 'on']
      vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'USRP0',
                    '--vendorid', '0x2500', '--productid', '0x0021']
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    nitb.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.host_key_checking = false
      ansible.playbook = "deploy/nitb.yml"
      ansible.raw_arguments = ['--timeout=20']
      ansible.verbose = 'v'
    end
  end

end
