---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- hosts: web
  gather_facts: True
  become_user: root
  become: True
  vars:
    ansible_ssh_pipelining: true
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US
    LC_CTYPE: en_US.UTF-8
    LC_NUMERIC: en_US.UTF-8
    LC_TIME: en_US.UTF-8
    LC_COLLATE: en_US.UTF-8
    LC_MONETARY: en_US.UTF-8
    LC_MESSAGES: en_US.UTF-8
    LC_PAPER: en_US.UTF-8
    LC_NAME: en_US.UTF-8
    LC_ADDRESS: en_US.UTF-8
    LC_TELEPHONE: en_US.UTF-8
    LC_MEASUREMENT: en_US.UTF-8
    LC_IDENTIFICATION: en_US.UTF-8
  tasks:
    - name: Add basic packages for operation
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
          - build-essential
          - python

    - name: Add the key for the nodesource apt repository
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    - name: Add the nodesource repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
        update_cache: yes

    - name: install nodejs
      apt: name=nodejs

    - name: Install 5 Bells Ledger
      npm:
        name: five-bells-ledger
        state: present
        global: yes
