---

- name: Set up a network in a box on a local virtual machine
  hosts: nitb
  become: yes

  tasks:

    - name: Add Osmocom apt GPG key
      apt_key:
          url: https://download.opensuse.org/repositories/network:/osmocom:/nightly/Debian_9.0/Release.key
          state: present

    # TODO(issues/6) Convert to the latest branch when stable and ready for deployment.
    - name: Add Osmocom Debian 9 nightly repo
      apt_repository:
          repo: 'deb http://download.opensuse.org/repositories/network:/osmocom:/nightly/Debian_9.0 ./'
          update_cache: no
          mode: 664
      register: osmocom_repo

    - name: Run the equivalent of "apt-get update" as a separate step
      when: osmocom_repo.changed
      apt:
          update_cache: yes

    - name: Install utilities for terminal interaction
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - fish
          - tmux
          - python3-dev
          - emacs-nox
          - usbutils

    - name: Install uhd drivers for USRP
      apt: pkg={{ item }} state=present
      with_items:
          - libuhd-dev
          - libuhd003
          - uhd-host
        
