---

- name: Set up a network in a box on a local virtual machine
  hosts: nitb
  roles:
    - { role: osmo-packet-core }
    - { role: osmo-bts-trx }
  become: yes

  tasks:
    - name: Install utilities for terminal interaction
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - fish
          - tmux
          - python3-dev
          - emacs-nox
          - usbutils

    - name: Copy osmocom configuration files
      copy:
        src: "{{ item }}"
        dest: /etc/osmocom/
        force: yes
      with_fileglob:
        - ../config/nitb/*

    - name: Copy osmocom service files
      copy:
        src: "{{ item }}"
        dest: /lib/systemd/system/
        force: yes
      with_fileglob:
        - ../config/systemd/*
      register: osmocom_services

    - name: Reload systemd daemon if necessary
      when: osmocom_services.changed
      command: systemctl daemon-reload

    - name: Mask the default Osmocom unit files
      service:
        name: "{{ item }}"
        enabled: no
        masked: yes
        no_block: yes
        state: stopped
      with_items:
          - osmo-hlr
          - osmo-msc
          - osmo-mgw
          - osmo-stp
          - osmo-bsc
          - osmo-bts-trx
          - osmo-ggsn
          - osmo-sgsn
          - osmo-pcu
